### PR TITLE
fix(install): set rengine folder correctly & fix non interactive argument check

### LINKED ISSUE #247: bug(install): post install script failed to run
### Current Behavior

I forgot to update some others places for the working dir during install.
This leads to fail creation of the superuser and some others actions in the Makefile

Image

### Expected Behavior

Install and Makefile commands should run successfully

### Steps To Reproduce

1. Clone dir
2. install reNgine-ng or launch Django commands from Makefile

### Environment

```markdown
- reNgine: 2.1.1
- OS: debian 12
- Python: 3.10
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Anything else?

_No response_

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by psyray**
Fix #247

- Define and uses a new environment variable, RENGINE_FOLDER, to specify the reNgine installation directory. 
- Fix non interactive argument check not working while using sudo command

  - [x] Test install
  - [x] Test non interactive install

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -195,12 +195,25 @@ main() {
...
 
   isNonInteractive=false
-  while getopts nh opt; do
-     case $opt in
-        n) isNonInteractive=true ;;
-        h) usageFunction ;;
-        ?) usageFunction ;;
-     esac
+  # Get args from sudo or directly
+  args="${@:-${SUDO_COMMAND#*/install.sh }}"
```
Comment (AnonymousWP) [inline install.sh:199]: Not exactly understandable/readable, because `SUDO_COMMAND` is defined nowhere, so it'll be set anyway.

**Review by AnonymousWP — APPROVED** [review]
Small comment, but nothing significant, so approving anyway.

File: install.sh (hunk 1 above)
Comment (psyray) [reply install.sh:199]: https://askubuntu.com/a/953497

SUDO_COMMAND is an environment variable set by sudo only in the environment of the process started by it (and inherited by any child processes).
