### PR TITLE
fix(install): remove duplicated code in install script

### LINKED ISSUE #264: bug(install): Error: INSTALL_TYPE is not set in non interactive install
### Current Behavior

This error displays when trying to install in non interactive mode (-n)
Error: INSTALL_TYPE is not set in non interactive install

### Expected Behavior

Non interactive install should work

### Steps To Reproduce

1. run sudo ./install.sh -n on a fresh install

### Environment

```markdown
- reNgine: 2.1.1
- OS: Debiian 12
- Python: 3.10
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Anything else?

_No response_

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by psyray**
fix #264 

Tested and working

## Summary by Sourcery

Build:
- Set default `INSTALL_TYPE` to `prebuilt` for non-interactive installations.

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -236,49 +236,43 @@ main() {
...
+  else
+      current_id=$(id -u)
+  fi
 
-log "Selected installation type: $INSTALL_TYPE" $COLOR_CYAN
+  # Install type
+  if [ "$current_id" -ne 1000 ]; then
+      # If the user is not 1000, force source install because pre-built images are not compatible with user > 1000
+      INSTALL_TYPE="source"
+      log "Build has been forced because your user ID is not the same as the pre-built images. If you want to use pre-built images, your current user installing reNgine-ng must be 1000." $COLOR_RED
```
Comment (AnonymousWP) [inline install.sh:249]: Do we need to explain/outline how to do this or do you assume this to be common knowledge (first/primary user of the OS)?

File: install.sh [hunk 2]
```diff
@@ -236,49 +236,43 @@ main() {
...
+  else
+      if [ "$isNonInteractive" = false ]; then
+          log "Do you want to build Docker images from source or use pre-built images (recommended)? \nThis saves significant build time but requires good download speeds for it to complete fast." $COLOR_RED
```
Comment (AnonymousWP) [inline install.sh:252]:
```suggestion
          log "Do you want to build Docker images from source or use pre-built images (recommended)?\nThis saves significant build time but requires good download speeds for it to complete fast." $COLOR_RED
```

Otherwise this creates a redundant space.

**Review by AnonymousWP — CHANGES_REQUESTED** [review]

File: install.sh (hunk 1 above)
Comment (psyray) [reply install.sh:249]: I've updated the wiki with steps to do this
image

Comment (AnonymousWP) [reply install.sh:249]: Great. We should definitely also include this in our changelog though. Maybe add a "breaking changes" header?

Comment (psyray) [reply install.sh:249]: Already there
image

Comment (psyray) [reply install.sh:249]: I will add create a sudo user

Comment (AnonymousWP) [reply install.sh:249]: I mean in the changelog of the release.

Comment (AnonymousWP) [reply install.sh:249]: But what we can also do, is just link to wherever these breaking changes are, if you know what I mean.

Comment (psyray) [reply install.sh:249]: > I mean in the changelog of the release.

We need to update it :grin: 
https://github.com/Security-Tools-Alliance/rengine-ng/blob/master/CHANGELOG.md
image

For the moment, only the Changelog in the wiki is up to date

**Comment by psyray** [comment]
- [x] Rebased and tested

**Review by sundayz-hunter — APPROVED** [review]
I have retested the script in both interactive and non-interactive installation modes.
I ran tests with users having GID 1000 as well as different GID and UID combinations, and everything worked flawlessly!

Additionally, the modifications to the wiki are clear and well-documented.

Great job! 🚀

**Comment by psyray** [comment]
> I have retested the script in both interactive and non-interactive installation modes. I ran tests with users having GID 1000 as well as different GID and UID combinations, and everything worked flawlessly!
> 
> Additionally, the modifications to the wiki are clear and well-documented.
> 
> Great job! 🚀

Great, thanks for this complete testing :+1:

File: install.sh (hunk 1 above)
Comment (AnonymousWP) [reply install.sh:345]: Let's discuss this on Discord how we'll set this up correctly.

**Review by AnonymousWP — APPROVED** [review]
