### PR TITLE
fix(tools): update git tools at startup

### LINKED ISSUE #15: bug: Error creating EyeWitness screenshots with a non-standard URL
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Submitted by @solo10010

The task of creating screenshots stops completely if EyeWitness encounters a strange URL

```
python3 /usr/src/github/EyeWitness/Python/EyeWitness.py -f /usr/src/scan_results/**********.com_9/endpoints_alive.txt -d /usr/src/scan_results/* *********.com_9/screenshots --no-prompt --timeout 10 --threads 40

Scan logs.

TERM environment variable not set.
################################################## ###############################
#EyeWitness#
################################################## ###############################
# Red Siege Information Security - https://www.redsiege.com #
################################################## ###############################

ERROR: You potentially provided an mal-formed URL!
ERROR: URL is - https://account.servicenow.com/sign-in?client_id=0oapi9ote73XCWSst0x7&redirect_uri=https://account.servicenow.com/auth&response_type=code&state=/profile/home?locale=en-us&scope=openid&source_id= account&locale=en-us
```

### Expected Behavior

I expected that if errors occurred, the collection of screenshots would continue and not be interrupted completely.

### Steps To Reproduce

1. Install the latest version of rengine
2. Set up any scan with collection of subdomains and creation of screenshots for the servicenow.com domain
3. Monitor scanning tasks, screenshot creation has been stopped on the account.servicenow.com subdomain

### Environment

```markdown
- reNgine: 2.0.2
- OS: Ubuntu 22.04.1 LTS.
- Python: 3.10.4
- Docker engine: 24.0.7
- Docker Compose: v2.23.0
- Browser: Chrome 120.0.6099.224.
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by psyray**
Fix #15 

Read issue for details

As **EyeWitness** has been [patched](https://github.com/Security-Tools-Alliance/rengine-ng/issues/15#issuecomment-2146609574), the bug above should be fixed when you restart the celery container, but not ...
So I've added a condition, when directory exists, for every tool, to update it by git pulling

So now **EyeWitness** bug need a simple `make stop`, `make restart` to be fixed

I've also:
- silent the **pip** output that makes the status of the tools update not visible
- fixed a small path bug for **gf**, this could improve things because this fix prevent the **tomnomnom** gf pattern copy to fail

Tested and working

### CODE REVIEW

File: web/celery-entrypoint.sh [hunk 1]
```diff
@@ -19,8 +19,8 @@ Package: firefox
 Pin: version 1:1snap1-0ubuntu2
 Pin-Priority: -1
 ' | tee /etc/apt/preferences.d/mozilla-firefox
-apt update
-apt install firefox -y
+apt-get update
+apt-get install firefox -y
```
Comment (AnonymousWP) [inline web/celery-entrypoint.sh:23]: Why adding `-get` actually? That shouldn't be needed anymore.

Comment (psyray) [reply web/celery-entrypoint.sh:23]: yes my bad, i forget to reset to apt.
I've done some tests to silent apt a little with no luck

Comment (psyray) [reply web/celery-entrypoint.sh]: Fixed

**Review by AnonymousWP — APPROVED** [review]
